"""
See https://pmc.ncbi.nlm.nih.gov/articles/PMC11655964/

Based on the findings in this publication, detection of diagnostic candidates between different Exomiser analysis
versions could be assisted through a minimal search:
 - when comparing two different Exomiser release versions
 - if a Variant score was > 0.8
 - and a Phenotype score had increased between releases by 0.2 or more

This script takes two Exomiser aggregated result sets (generated by this workflow) and detects this delta, publishing
variants which satisfy these criteria
"""

import json
from argparse import ArgumentParser
from collections import defaultdict

from cloudpathlib.anypath import to_anypath


VAR_SCORE_THRESHOLD = 0.8
VAR_SCORE_KEY = 'variant_score'
PHENO_SCORE_THRESHOLD = 0.2
PHENO_SCORE_KEY = 'phenotype_score'
INTERMEDIATE_TYPE = dict[str, dict[str, dict[str, str | float]]]


def parse_json(input_file: str) -> INTERMEDIATE_TYPE:
    """
    Read a file!
    """

    results = {}

    with to_anypath(input_file).open() as handle:
        json_data = json.load(handle)

    for sample_id, variants in json_data.items():
        results[sample_id] = {}
        for variant_id, content_list in variants.items():
            # content_list here is really just one entry, not sure why I did it this way
            results[sample_id][variant_id] = content_list[0]
    return results


def compare_two_result_sets(old_parsed: INTERMEDIATE_TYPE, new_parsed: INTERMEDIATE_TYPE) -> INTERMEDIATE_TYPE:
    """
    compare the two objects, storing only instances where a sample is in both datasets
    and a variant fits the selection criteria
    """
    upgrades = defaultdict(lambda: defaultdict(dict))

    for sample_id in old_parsed:
        # only interested in common results
        if sample_id not in new_parsed:
            continue

        for variant_id in old_parsed[sample_id]:
            # and again, common variants only
            if variant_id not in new_parsed[sample_id]:
                continue

            old_data = old_parsed[sample_id][variant_id]
            new_data = new_parsed[sample_id][variant_id]

            if float(new_data[VAR_SCORE_KEY]) <= VAR_SCORE_THRESHOLD:
                continue

            delta = float(new_data[PHENO_SCORE_KEY]) - float(old_data[PHENO_SCORE_KEY])
            if delta < PHENO_SCORE_THRESHOLD:
                continue

            new_data['version_delta'] = delta

            # good, keep this
            upgrades[sample_id][variant_id] = new_data

    return dict(upgrades)


def main(old_input: str, new_input: str, output: str):
    """
    step 1: read results in
    step 2: compare old(er) and new(er) results, looking for the indicated upgrade
    step 3: if found, write new content containing just these indications

    Args:
        old_input: str, path to an older Exomiser result set
        new_input: str, path to a newer Exomiser result set
        output: str, path to an output file
    """

    old_parsed = parse_json(old_input)
    new_parsed = parse_json(new_input)

    # now for the comparison
    upgrades = compare_two_result_sets(old_parsed, new_parsed)

    if not upgrades:
        raise RuntimeError(f'No changes detected between {old_input} and {new_input}')

    with to_anypath(output).open('w') as handle:
        json.dump(upgrades, handle, indent=4)


if __name__ == '__main__':
    parser = ArgumentParser()
    parser.add_argument('--previous', help='Earlier Exomiser results')
    parser.add_argument('--latest', help='Latest Exomiser results')
    parser.add_argument('--output', help='Incremental results satisfying heuristic for attention')
    args = parser.parse_args()
    main(old_input=args.previous, new_input=args.latest, output=args.output)
