[workflow]
name = 'exomiser'
status_reporter = 'metamist'

exomiser_version = '14.1.0'
exomiser_data_version = '2502'

# in addition to these fields, you will need to supply input_cohorts, and a sequencing_type
# cpg-flow will use this to query metamist, and set up the pipeline framework

# attributes to provision the Exomiser VMs
# Much lower storage req. - CADD & REMM not in use
exomiser_memory = '60Gi'
exomiser_storage = '100Gi'
exomiser_cpu = 4

# change this down to 13 to select the previous version of exomiser
exomiser_version = 14

# number of exomiser jobs to fit onto each VM
exomiser_chunk_size = 8

# number of jobs to run in parallel through backgrounded processes
exomiser_parallel_chunks = 4

# used to make sure we don't repeat previously completed stages
check_expected_outputs = true

[images]
bcftools = "australia-southeast1-docker.pkg.dev/cpg-common/images/bcftools:1.21-2"
exomiser = "australia-southeast1-docker.pkg.dev/cpg-common/images/exomiser:14.1.0-1"

[references]
exomiser_2402_pheno = "gs://cpg-common-main/references/exomiser_2402/phenotype"
exomiser_2402_core = "gs://cpg-common-main/references/exomiser_2402/core"
exomiser_2502_pheno = "gs://cpg-common-main/references/exomiser_2502/phenotype"
exomiser_2502_core = "gs://cpg-common-main/references/exomiser_2502/core"
